"""
Django settings for linkedin project.

Generated by 'django-admin startproject' using Django 4.2.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
# BASE_DIR = Path(__file__).resolve().parent.parent

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-hv+@a94gz1f-sm720=0-@e)_y2ah!od4rdi%1)u3=u&5@+4s3)'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

# ALLOWED_HOSTS = ['bitekexchange.com/cryptoflow/', 'www.bitekexchange.com/cryptoflow/.com', '127.0.0.1', 'localhost']

ADMIN_EMAILS = ('carksonniit@gmail.com', 'carksond@gmail.com')


# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'core',
]


JAZZMIN_SETTINGS = {
    "site_title": "Linkedin",
    "site_header": "Linkedin",
    "welcome_sign": "Welcome to Linkedin Dashboard",
    "site_brand": "Linkedin",
    "show_ui_builder": True, 
    # "site_logo": "img/favicon-32x32.png",
    # "login_logo": "img/logo-white.png",
    "custom_css": "css/custom_login.css",
    # "login_logo_dark": None,
}

JAZZMIN_UI_TWEAKS = {
    "navbar_small_text": False,
    "footer_small_text": False,
    "body_small_text": False,
    "brand_small_text": False,
    "brand_colour": False,
    "accent": "accent-primary",
    "navbar": "navbar-blue",
    "no_navbar_border": False,
    "navbar_fixed": True,
    "layout_boxed": False,
    "footer_fixed": False,
    "sidebar_fixed": True,
    "sidebar": "sidebar-dark-primary",
    "sidebar_nav_small_text": False,
    "sidebar_disable_expand": True,
    "sidebar_nav_child_indent": False,
    "sidebar_nav_compact_style": False,
    "sidebar_nav_legacy_style": False,
    "sidebar_nav_flat_style": True,
    "theme": "darkly",  # Default Bootstrap theme
    "dark_mode_theme": "",  # Setting the dark mode theme
    "button_classes": {
        "primary": "btn-outline-primary",
        "secondary": "btn-outline-secondary",
        "info": "btn-outline-info",
        "warning": "btn-outline-warning",
        "danger": "btn-outline-danger",
        "success": "btn-outline-success",
    },
}


EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'mail.kennylass.com.ng'
EMAIL_PORT = 587
# EMAIL_PORT = 465
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'info@kennylass.com.ng'
EMAIL_HOST_PASSWORD = 'CeroW4xDByI%'
DEFAULT_FROM_EMAIL = 'info@kennylass.com.ng'


MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware', #for the language translation
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]


# this feature is a helper to the language translation
from django.utils.translation import gettext_lazy as _


LANGUAGES = [
    ('ar', _('Arabic')),                # العربية
    ('bn', _('Bangla')),                # বাংলা
    ('cs', _('Czech')),                 # Čeština
    ('da', _('Danish')),                # Dansk
    ('de', _('German')),                # Deutsch
    ('el', _('Greek')),                 # Ελληνικά
    ('en', _('English')),               # English
    ('es', _('Spanish')),               # Español
    ('fa', _('Persian')),               # فارسی
    ('fi', _('Finnish')),               # Suomi
    ('fr', _('French')),                # Français
    ('hi', _('Hindi')),                 # हिंदी
    ('hu', _('Hungarian')),             # Magyar
    ('id', _('Indonesian')),            # Bahasa Indonesia
    ('it', _('Italian')),               # Italiano
    ('he', _('Hebrew')),                # עברית (note: 'iw' is old code, 'he' is preferred)
    ('ja', _('Japanese')),              # 日本語
    ('ko', _('Korean')),                # 한국어
    ('mr', _('Marathi')),               # मराठी
    ('ms', _('Malay')),                 # Bahasa Malaysia
    ('nl', _('Dutch')),                 # Nederlands
    ('no', _('Norwegian')),             # Norsk
    ('pa', _('Punjabi')),               # ਪੰਜਾਬੀ
    ('pl', _('Polish')),                # Polski
    ('pt', _('Portuguese')),            # Português
    ('ro', _('Romanian')),              # Română
    ('ru', _('Russian')),               # Русский
    ('sv', _('Swedish')),               # Svenska
    ('te', _('Telugu')),                # తెలుగు
    ('th', _('Thai')),                  # ภาษาไทย
    ('tl', _('Tagalog')),               # Tagalog
    ('tr', _('Turkish')),               # Türkçe
    ('uk', _('Ukrainian')),             # Українська
    ('vi', _('Vietnamese')),            # Tiếng Việt
    ('zh-hans', _('Chinese (Simplified)')),  # 简体中文
    ('zh-hant', _('Chinese (Traditional)')), # 正體中文
]

LOCALE_PATHS = [
    os.path.join(BASE_DIR, 'locale'),
]

LANGUAGE_CODE = 'en'





ROOT_URLCONF = 'linkedin.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'linkedin.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
        
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

# STATIC_URL = 'static/'

# Cpanel static settings

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'vcabukhw/public_html/media/')


STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'home/vcabukhw/public_html/static/') 
STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'home/vcabukhw/public_html/assets/') 

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
    
]

STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'


# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
